# Generated by Django 5.0.4 on 2024-05-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('equipamento', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(max_length=100)),
            ],
        ),
    ]
